import { FormEvent, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { foundationApi, organizationApi, schoolApi } from "../services/api";
import { useAuthStore } from "../store/authStore";
import { FormField as Field, StatusAlert as Alert } from "../components/ui/FormControls";
import { canManageOrganizationAcademicYears, usesOrganizationAcademicYears } from "../utils/academicYears";
import { apiErrorMessage } from "../utils/apiError";
import type { AcademicYear, OrganizationAcademicYear, School } from "../types";

type YearRow = OrganizationAcademicYear | AcademicYear;

export default function AcademicYearsPage(){
  const {schoolId=""}=useParams(); const user=useAuthStore(s=>s.user);
  const canManage=canManageOrganizationAcademicYears(user);
  const [school,setSchool]=useState<School|null>(null),[years,setYears]=useState<YearRow[]>([]),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [form,setForm]=useState({code:"2026-27",name:"Academic Year 2026-27",starts_on:"2026-06-01",ends_on:"2027-05-31",notes:""});
  const [editing,setEditing]=useState<OrganizationAcademicYear|null>(null),[editForm,setEditForm]=useState({code:"",name:"",starts_on:"",ends_on:"",notes:""});
  const tenantMode=usesOrganizationAcademicYears(user);
  const load=async()=>{setError("");try{const sc=await schoolApi.get(schoolId);setSchool(sc);if(tenantMode&&sc.organization_id){setYears(await organizationApi.academicYears(sc.organization_id));}else{const campuses=await foundationApi.campuses(schoolId);const campus=campuses.find(c=>c.id===user?.campus_id)||campuses[0];setYears(campus?await foundationApi.academicYears(campus.id):[]);}}catch(e){setError(apiErrorMessage(e,"Failed to load academic years"));}};
  useEffect(()=>{if(schoolId)void load()},[schoolId,user?.campus_id]);
  const create=async(e:FormEvent)=>{e.preventDefault();if(!school?.organization_id)return;setError("");setMessage("");try{await organizationApi.createAcademicYear(school.organization_id,{...form,notes:form.notes||null});setMessage("Academic year created for the organization and synchronized to its campuses.");await load();}catch(e){setError(apiErrorMessage(e,"Failed to create academic year"));}};
  const beginEdit=(y:YearRow)=>{if(!canManage||!("organization_id" in y))return;const oy=y as OrganizationAcademicYear;setEditing(oy);setEditForm({code:oy.code,name:oy.name,starts_on:oy.starts_on,ends_on:oy.ends_on,notes:oy.notes||""});setError("");setMessage("");};
  const saveEdit=async(e:FormEvent)=>{e.preventDefault();if(!editing)return;setError("");setMessage("");try{const payload=editing.status==="draft"?{...editForm,notes:editForm.notes||null}:{name:editForm.name,notes:editForm.notes||null};await organizationApi.updateAcademicYear(editing.id,payload);setEditing(null);setMessage("Academic year updated and synchronized to campuses.");await load();}catch(e){setError(apiErrorMessage(e,"Failed to update academic year"));}};
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Academic Years</h1><p className="text-gray-500 mt-1">Academic-year dates are organization-wide and synchronized to all campuses.</p></div>{error&&<Alert kind="error" text={error}/>} {message&&<Alert kind="success" text={message}/>} 
  {canManage&&<form onSubmit={create} className="card grid grid-cols-1 md:grid-cols-2 gap-4"><div className="md:col-span-2"><h2 className="font-semibold">Create Academic Year</h2></div><Field label="Code" value={form.code} onChange={v=>setForm({...form,code:v})}/><Field label="Name" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Starts On" type="date" value={form.starts_on} onChange={v=>setForm({...form,starts_on:v})}/><Field label="Ends On" type="date" value={form.ends_on} onChange={v=>setForm({...form,ends_on:v})}/><Field label="Notes" value={form.notes} onChange={v=>setForm({...form,notes:v})} required={false}/><div className="md:col-span-2"><button className="btn-primary">Create Academic Year</button></div></form>}
  {!canManage&&<div className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-800">View-only. You can view Academic Years and their current state. Organization Admin or Platform Super Admin can create or modify them.</div>}
  {editing&&<form onSubmit={saveEdit} className="card grid grid-cols-1 md:grid-cols-2 gap-4"><div className="md:col-span-2"><h2 className="font-semibold">Edit Academic Year</h2><p className="text-xs text-gray-500 mt-1">For active or historical years, code and date boundaries are locked; name and notes remain editable.</p></div><Field label="Code" value={editForm.code} onChange={v=>setEditForm({...editForm,code:v})} disabled={editing.status!=="draft"}/><Field label="Name" value={editForm.name} onChange={v=>setEditForm({...editForm,name:v})}/><Field label="Starts On" type="date" value={editForm.starts_on} onChange={v=>setEditForm({...editForm,starts_on:v})} disabled={editing.status!=="draft"}/><Field label="Ends On" type="date" value={editForm.ends_on} onChange={v=>setEditForm({...editForm,ends_on:v})} disabled={editing.status!=="draft"}/><Field label="Notes" value={editForm.notes} onChange={v=>setEditForm({...editForm,notes:v})} required={false}/><div className="md:col-span-2 flex gap-2"><button className="btn-primary">Save Changes</button><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Cancel</button></div></form>}
  <section className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Code</th><th>Name</th><th>Dates</th><th>State / Status</th><th>Actions</th></tr></thead><tbody>{years.map(y=><tr className="border-b last:border-0" key={y.id}><td className="py-3 font-medium">{y.code}</td><td>{y.name}</td><td>{y.starts_on} → {y.ends_on}</td><td className="capitalize">{y.status}</td><td><div className="flex gap-2">{canManage&&"organization_id" in y&&<button className="btn-secondary" onClick={()=>beginEdit(y)}>Edit</button>}{canManage&&"organization_id" in y&&y.status!=="active"&&<button className="btn-secondary" onClick={async()=>{try{await organizationApi.activateAcademicYear(y.id);await load()}catch(e){setError(apiErrorMessage(e,"Failed to activate academic year"))}}}>Activate</button>}</div></td></tr>)}</tbody></table>{years.length===0&&<div className="py-8 text-center text-gray-500">No academic years configured.</div>}</section></div>;
}
