import { useEffect, useState } from "react";
import { Cloud, DatabaseBackup, Download, RotateCcw, ShieldCheck, Trash2 } from "lucide-react";
import { systemApi, type BackupItem, type BackupStatus } from "../services/api";
import { apiErrorMessage } from "../utils/apiError";

export default function BackupRestorePage(){
 const [items,setItems]=useState<BackupItem[]>([]),[schedule,setSchedule]=useState(24),[retention,setRetention]=useState(30),[status,setStatus]=useState<BackupStatus|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{try{const d=await systemApi.backups();setItems(d.items);setSchedule(d.schedule_hours);setRetention(d.retention_count);setStatus(d.status);}catch(e){setError(apiErrorMessage(e,"Failed to load backup history"));}};
 useEffect(()=>{void load()},[]);
 const create=async()=>{setBusy(true);setError("");setMessage("");try{const b=await systemApi.createBackup();setMessage(`Backup created: ${b.name}${b.offsite?.configured?(b.offsite.synced?" · off-site copy verified":" · off-site copy failed"):""}`);await load();}catch(e){setError(apiErrorMessage(e,"Backup failed"));}finally{setBusy(false)}};
 const download=async(item:BackupItem)=>{try{const blob=await systemApi.downloadBackup(item.name);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=item.name;a.click();URL.revokeObjectURL(url);}catch(e){setError(apiErrorMessage(e,"Backup download failed"));}};
 const remove=async(item:BackupItem)=>{if(!confirm(`Delete local backup ${item.name}? Off-site retention is managed separately.`))return;try{await systemApi.deleteBackup(item.name);await load();}catch(e){setError(apiErrorMessage(e,"Backup delete failed"));}};
 const restore=async(item:BackupItem)=>{const phrase=prompt(`Restore ${item.name}?\nThis is destructive and maintenance-gated. Type RESTORE DATABASE to continue.`);if(phrase!=="RESTORE DATABASE")return;setBusy(true);try{await systemApi.restore(item.name,item.sha256,phrase);setMessage(`Restore completed from ${item.name}. A pre-restore safety backup was created.`);await load();}catch(e){setError(apiErrorMessage(e,"Restore was not completed"));}finally{setBusy(false)}};
 return <div className="space-y-6"><div className="flex justify-between gap-4"><div><h1 className="text-2xl font-bold">Backup & Restore</h1><p className="text-gray-500 mt-1">PostgreSQL recovery controls, checksum verification and optional off-site replication. Platform Owner only.</p></div><button className="btn-primary inline-flex items-center gap-2" onClick={()=>void create()} disabled={busy}><DatabaseBackup size={18}/>{busy?"Working…":"Create Backup"}</button></div>{error&&<div className="rounded-lg bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">{error}</div>}{message&&<div className="rounded-lg bg-green-50 border border-green-200 text-green-700 px-4 py-3 text-sm">{message}</div>}
 <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4"><div className="card"><div className="text-sm text-gray-500">Scheduled backup</div><div className="text-xl font-semibold mt-1">Every {schedule} hours</div></div><div className="card"><div className="text-sm text-gray-500">Local retention</div><div className="text-xl font-semibold mt-1">Latest {retention}</div><div className="text-xs text-gray-500 mt-1">Current local recovery points: {status?.local_count??items.length}</div></div><div className="card"><div className="flex items-center gap-2 text-sm text-gray-500"><Cloud size={16}/>Off-site copy</div><div className="text-xl font-semibold mt-1">{status?.offsite_configured?"Configured":"Not configured"}</div><div className="text-xs text-gray-500 mt-1">{status?.offsite_count??0} recovery points</div></div><div className="card"><div className="flex items-center gap-2 text-sm text-gray-500"><ShieldCheck size={16}/>Archive safety</div><div className={`text-xl font-semibold mt-1 ${status?.recent_backup_ready_for_archive?"text-green-700":"text-amber-700"}`}>{status?.recent_backup_ready_for_archive?"Backup ready":"Backup needed"}</div><div className="text-xs text-gray-500 mt-1">Recent = within {status?.archive_backup_max_age_hours??24} hours</div></div></div>
 {status&&<div className="card"><h2 className="font-semibold">Retention Policy</h2><div className="mt-3 grid sm:grid-cols-4 gap-3 text-sm"><div><div className="text-gray-500">Local</div><div className="font-semibold">{status.retention.local_latest} latest</div></div><div><div className="text-gray-500">Daily off-site</div><div className="font-semibold">{status.retention.daily_days} days</div></div><div><div className="text-gray-500">Weekly off-site</div><div className="font-semibold">{status.retention.weekly_weeks} weeks</div></div><div><div className="text-gray-500">Monthly off-site</div><div className="font-semibold">{status.retention.monthly_months} months</div></div></div></div>}
 <section className="card overflow-x-auto"><h2 className="font-semibold mb-4">Local Backup History</h2><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">Created</th><th>Backup</th><th>Size</th><th>SHA-256</th><th>Actions</th></tr></thead><tbody>{items.map(i=><tr key={i.name} className="border-b last:border-0"><td className="py-3 whitespace-nowrap">{new Date(i.created_at).toLocaleString()}</td><td className="font-mono text-xs">{i.name}</td><td>{(i.size_bytes/1024/1024).toFixed(2)} MB</td><td className="font-mono text-xs max-w-40 truncate" title={i.sha256}>{i.sha256}</td><td><div className="flex gap-2"><button className="btn-secondary" title="Download" onClick={()=>void download(i)}><Download size={16}/></button><button className="btn-secondary" title="Restore" onClick={()=>void restore(i)} disabled={busy}><RotateCcw size={16}/></button><button className="btn-secondary" title="Delete local copy" onClick={()=>void remove(i)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{items.length===0&&<div className="py-8 text-center text-gray-500">No backups yet.</div>}</section><div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Restore is disabled by default. Enable <code>BROWSER_RESTORE_ENABLED=true</code> only during an approved maintenance window. Set <code>BACKUP_OFFSITE_DIR</code> to a separate disk, network share, or externally synchronized storage location. Direct cloud-provider integration can be selected when the production hosting provider is finalized.</div></div>
}
