import { FormEvent, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { academicApi, foundationApi } from "../services/api";
import { useAuthStore } from "../store/authStore";
import { hasPermission } from "../utils/permissions";
import { canImportClassesAndSections } from "../utils/bulkImports";
import { apiErrorMessage } from "../utils/apiError";
import type { AcademicClass, Campus, Section } from "../types";

export default function ClassesSectionsPage(){
 const {schoolId=""}=useParams();const user=useAuthStore(s=>s.user);const canManage=hasPermission(user,"academic_class.manage");const canBulk=canImportClassesAndSections(user);
 const [campuses,setCampuses]=useState<Campus[]>([]),[campusId,setCampusId]=useState(""),[classes,setClasses]=useState<AcademicClass[]>([]),[sections,setSections]=useState<Record<string,Section[]>>({}),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [classForm,setClassForm]=useState({code:"",name:""}),[sectionForm,setSectionForm]=useState({class_id:"",code:"",name:""});
 const [editClass,setEditClass]=useState<AcademicClass|null>(null),[editClassForm,setEditClassForm]=useState({code:"",name:""});
 const [editSection,setEditSection]=useState<Section|null>(null),[editSectionForm,setEditSectionForm]=useState({code:"",name:""});
 const loadCampuses=async()=>{try{const c=await foundationApi.campuses(schoolId);setCampuses(c);setCampusId(x=>x||user?.campus_id||c[0]?.id||"");}catch(e){setError(apiErrorMessage(e,"Failed to load campuses"));}};
 useEffect(()=>{if(schoolId)void loadCampuses()},[schoolId,user?.campus_id]);
 const loadClasses=async()=>{if(!campusId)return;try{const cls=await academicApi.classes(campusId);setClasses(cls);const pairs=await Promise.all(cls.map(async c=>[c.id,await academicApi.sections(c.id)] as const));setSections(Object.fromEntries(pairs));setSectionForm(f=>({...f,class_id:f.class_id&&cls.some(c=>c.id===f.class_id)?f.class_id:cls[0]?.id||""}));}catch(e){setError(apiErrorMessage(e,"Failed to load classes and sections"));}};
 useEffect(()=>{void loadClasses()},[campusId]);
 const createClass=async(e:FormEvent)=>{e.preventDefault();setError("");try{await academicApi.createClass(campusId,{code:classForm.code.trim(),name:classForm.name.trim()});setClassForm({code:"",name:""});setMessage("Class created. Display order is assigned automatically.");await loadClasses();}catch(e){setError(apiErrorMessage(e,"Failed to create class"));}};
 const createSection=async(e:FormEvent)=>{e.preventDefault();setError("");try{await academicApi.createSection(sectionForm.class_id,{code:sectionForm.code.trim(),name:sectionForm.name.trim()});setSectionForm(f=>({...f,code:"",name:""}));setMessage("Section created.");await loadClasses();}catch(e){setError(apiErrorMessage(e,"Failed to create section"));}};
 const startClassEdit=(c:AcademicClass)=>{setEditClass(c);setEditClassForm({code:c.code,name:c.name});setEditSection(null)};
 const saveClass=async(e:FormEvent)=>{e.preventDefault();if(!editClass)return;try{await academicApi.updateClass(editClass.id,{code:editClassForm.code.trim(),name:editClassForm.name.trim()});setEditClass(null);setMessage("Class updated.");await loadClasses();}catch(e){setError(apiErrorMessage(e,"Failed to update class"));}};
 const startSectionEdit=(s:Section)=>{setEditSection(s);setEditSectionForm({code:s.code,name:s.name});setEditClass(null)};
 const saveSection=async(e:FormEvent)=>{e.preventDefault();if(!editSection)return;try{await academicApi.updateSection(editSection.id,{code:editSectionForm.code.trim(),name:editSectionForm.name.trim()});setEditSection(null);setMessage("Section updated.");await loadClasses();}catch(e){setError(apiErrorMessage(e,"Failed to update section"));}};
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Classes & Sections</h1><p className="text-gray-500 mt-1">Campus-level academic structure used by enrollment, fees and marks. Class display order is managed automatically.</p></div>{canBulk&&<Link className="btn-secondary" to={`/schools/${schoolId}/bulk-imports`}>Bulk Upload Classes & Sections</Link>}</div>{error&&<Alert text={error}/>} {message&&<div className="rounded-lg bg-green-50 border border-green-200 text-green-700 px-4 py-3 text-sm">{message}</div>}
 <section className="card"><label><span className="label">Campus / Branch</span><select className="input max-w-md" value={campusId} onChange={e=>setCampusId(e.target.value)}><option value="">Select campus</option>{campuses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></section>
 {canManage&&campusId&&<div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><form onSubmit={createClass} className="card grid grid-cols-1 md:grid-cols-2 gap-3"><div className="md:col-span-2"><h2 className="font-semibold">Create Class</h2></div><Field label="Code" value={classForm.code} onChange={v=>setClassForm({...classForm,code:v})}/><Field label="Name" value={classForm.name} onChange={v=>setClassForm({...classForm,name:v})}/><div className="md:col-span-2"><button className="btn-primary">Create Class</button></div></form>
 <form onSubmit={createSection} className="card grid grid-cols-1 md:grid-cols-3 gap-3"><div className="md:col-span-3"><h2 className="font-semibold">Create Section</h2></div><label><span className="label">Class</span><select className="input" value={sectionForm.class_id} onChange={e=>setSectionForm({...sectionForm,class_id:e.target.value})} required><option value="">Select</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label="Code" value={sectionForm.code} onChange={v=>setSectionForm({...sectionForm,code:v})}/><Field label="Name" value={sectionForm.name} onChange={v=>setSectionForm({...sectionForm,name:v})}/><div className="md:col-span-3"><button className="btn-primary">Create Section</button></div></form></div>}
 {editClass&&<form onSubmit={saveClass} className="card grid grid-cols-1 md:grid-cols-2 gap-3"><div className="md:col-span-2"><h2 className="font-semibold">Edit Class</h2></div><Field label="Code" value={editClassForm.code} onChange={v=>setEditClassForm({...editClassForm,code:v})}/><Field label="Name" value={editClassForm.name} onChange={v=>setEditClassForm({...editClassForm,name:v})}/><div className="md:col-span-2 flex gap-2"><button className="btn-primary">Save Changes</button><button type="button" className="btn-secondary" onClick={()=>setEditClass(null)}>Cancel</button></div></form>}
 {editSection&&<form onSubmit={saveSection} className="card grid grid-cols-1 md:grid-cols-2 gap-3"><div className="md:col-span-2"><h2 className="font-semibold">Edit Section</h2></div><Field label="Code" value={editSectionForm.code} onChange={v=>setEditSectionForm({...editSectionForm,code:v})}/><Field label="Name" value={editSectionForm.name} onChange={v=>setEditSectionForm({...editSectionForm,name:v})}/><div className="md:col-span-2 flex gap-2"><button className="btn-primary">Save Changes</button><button type="button" className="btn-secondary" onClick={()=>setEditSection(null)}>Cancel</button></div></form>}
 <section className="card"><h2 className="font-semibold mb-4">Academic Structure</h2><div className="space-y-3">{classes.map(c=><div key={c.id} className="rounded-lg border border-gray-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-medium">{c.name} <span className="text-xs text-gray-500">({c.code})</span></div>{canManage&&<button className="btn-secondary" onClick={()=>startClassEdit(c)}>Edit Class</button>}</div><div className="flex flex-wrap gap-2 mt-3">{(sections[c.id]||[]).map(s=><span className="rounded-lg bg-gray-100 px-3 py-2 text-xs flex items-center gap-2" key={s.id}>{s.name} ({s.code}){canManage&&<button className="underline text-primary-700" onClick={()=>startSectionEdit(s)}>Edit</button>}</span>)}{(sections[c.id]||[]).length===0&&<span className="text-sm text-gray-400">No sections</span>}</div></div>)}{classes.length===0&&<div className="py-8 text-center text-gray-500">No classes configured.</div>}</div></section></div>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span className="label">{label}</span><input className="input" type={type} value={value} onChange={e=>onChange(e.target.value)} required/></label>}
function Alert({text}:{text:string}){return <div className="rounded-lg bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">{text}</div>}
