import { FormEvent, useEffect, useState } from "react";
import { Bell, KeyRound, ShieldCheck } from "lucide-react";
import { subscriptionApi } from "../services/api";
import type { ActivationSchool, SubscriptionReminder } from "../types";
import { apiErrorMessage } from "../utils/apiError";

export default function ERPActivationPage(){
 const[schools,setSchools]=useState<ActivationSchool[]>([]),[reminders,setReminders]=useState<SubscriptionReminder[]>([]),[selected,setSelected]=useState(""),[code,setCode]=useState(""),[accepted,setAccepted]=useState(false),[termsVersion,setTermsVersion]=useState(""),[termsUrl,setTermsUrl]=useState<string|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{try{const[s,r,t]=await Promise.all([subscriptionApi.mySchools(),subscriptionApi.myReminders(),subscriptionApi.activationTerms()]);setSchools(s);setReminders(r);setTermsVersion(t.version);setTermsUrl(t.url||null);setSelected(v=>v||s.find(i=>i.activation_status!=="activated"&&i.activation_status!=="not_required")?.school_id||"");}catch(e){setError(apiErrorMessage(e,"Unable to load ERP activation."));}};
 useEffect(()=>{void load();},[]);
 const activate=async(e:FormEvent)=>{e.preventDefault();setError("");if(!accepted){setError("You must accept the Terms & Conditions before activation.");return}try{await subscriptionApi.activate(selected,code.trim(),accepted,termsVersion);setCode("");setAccepted(false);setNotice("School ERP activated successfully. Entitled modules and School user creation are now unlocked.");await load();}catch(err){setError(apiErrorMessage(err,"Activation failed."));}};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">ERP Activation</h1><p className="mt-1 text-gray-500">Activate schools in your organization. Payment and financial details remain with the Platform Owner.</p></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800">{notice}</div>}
 <form className="card" onSubmit={activate}><div className="flex gap-2"><KeyRound className="text-primary-700"/><h2 className="font-semibold">Activate a Paid School</h2></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label><span className="label">School</span><select className="input" required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select School</option>{schools.filter(s=>s.activation_status!=="not_required").map(s=><option key={s.school_id} value={s.school_id}>{s.school_name} · {s.activation_status.replace(/_/g," ")}</option>)}</select></label><label><span className="label">Activation Key</span><input className="input font-mono uppercase" required value={code} onChange={e=>setCode(e.target.value)} placeholder="SERP-ACT-..."/></label></div><label className="mt-4 flex items-start gap-2 rounded-lg border border-gray-200 p-3 text-sm"><input type="checkbox" className="mt-1" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I have read and accept the Terms & Conditions for this School activation{termsVersion?` (version ${termsVersion})`:""}.{termsUrl&&<> <a className="font-medium text-primary-700 underline" href={termsUrl} target="_blank" rel="noreferrer">View Terms & Conditions</a></>}</span></label><button className="btn-primary mt-4" disabled={!selected||!code.trim()||!accepted||!termsVersion}><ShieldCheck size={17}/>Activate School</button><p className="mt-3 text-xs text-gray-500">Paid Schools remain locked until payment eligibility, activation key and Terms acceptance are validated. Trial schools activate automatically with limited access and no download/export rights.</p></form>
 <section className="card overflow-x-auto"><h2 className="font-semibold">School Activation Status</h2><table className="mt-3 min-w-full text-sm"><thead><tr className="border-b text-left text-gray-500"><th className="py-2">School</th><th>Plan</th><th>Status</th><th>Expiry</th><th>Days</th></tr></thead><tbody>{schools.map(s=><tr key={s.school_id} className="border-b"><td className="py-3"><p className="font-medium">{s.school_name}</p><p className="text-xs text-gray-500">{s.school_code}</p></td><td>{s.plan_name}</td><td className="capitalize">{s.activation_status.replace(/_/g," ")}</td><td>{new Date(s.expires_at).toLocaleDateString()}</td><td>{s.days_remaining}</td></tr>)}</tbody></table></section>
 <section className="card"><div className="flex gap-2"><Bell/><h2 className="font-semibold">Platform Reminders</h2></div><div className="mt-3 space-y-2">{reminders.map(r=><div key={r.id} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><p>{r.message}</p><p className="mt-1 text-xs text-amber-700">{new Date(r.sent_at).toLocaleString()}</p></div>)}{!reminders.length&&<p className="text-sm text-gray-500">No reminders.</p>}</div></section>
 </div>;
}
