import { FormEvent, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { academicApi, erpAccessApi, feeApi, foundationApi, organizationApi, schoolApi } from "../services/api";
import { useAuthStore } from "../store/authStore";
import { hasPermission } from "../utils/permissions";
import type { AcademicClass, AcademicYear, Campus, Charge, FeeHead, FeeStructure, OrganizationAcademicYear, Section, FeeAccountStudent } from "../types";
import { apiErrorMessage } from "../utils/apiError";

export default function FeesPage() {
  const { schoolId = "" } = useParams();
  const user = useAuthStore((s) => s.user);
  const canCollect = hasPermission(user, "fee.collect");
  const canManageHeads = hasPermission(user, "fee.head.manage");
  const canManageStructures = hasPermission(user, "fee.structure.manage");
  const canManageERP = hasPermission(user, "erp_access.manage");
  const [students, setStudents] = useState<FeeAccountStudent[]>([]), [studentId, setStudentId] = useState(""), [charges, setCharges] = useState<Charge[]>([]);
  const [heads, setHeads] = useState<FeeHead[]>([]), [structures, setStructures] = useState<FeeStructure[]>([]), [campuses, setCampuses] = useState<Campus[]>([]), [years, setYears] = useState<AcademicYear[]>([]), [classes, setClasses] = useState<AcademicClass[]>([]), [sections, setSections] = useState<Section[]>([]);
  const [orgYears,setOrgYears]=useState<OrganizationAcademicYear[]>([]),[erpYearId,setErpYearId]=useState(""),[erpFeeHeadId,setErpFeeHeadId]=useState(""),[erpAmount,setErpAmount]=useState(""),[erpEnabled,setErpEnabled]=useState(true);
  const [selectedCampus, setSelectedCampus] = useState(""), [selectedClass, setSelectedClass] = useState(""), [error, setError] = useState(""), [message, setMessage] = useState("");
  const [headForm, setHeadForm] = useState({ code: "", name: "", is_misc: false });
  const [structureForm, setStructureForm] = useState({ campus_id: "", academic_year_id: "", academic_class_id: "", section_id: "", fee_head_id: "", frequency: "monthly", amount: "", due_date: "" });
  const [payment, setPayment] = useState({ mode: "cash", upi: "", amountByCharge: {} as Record<string, string> });

  const load = async () => {
    try {
      const [s, h, st, c, school] = await Promise.all([feeApi.accountStudents(schoolId), feeApi.heads(schoolId), feeApi.structures(schoolId), foundationApi.campuses(schoolId), schoolApi.get(schoolId)]);
      setStudents(s); setHeads(h); setStructures(st); setCampuses(c);
      if (c[0]) { setSelectedCampus(c[0].id); setStructureForm((f) => ({ ...f, campus_id: c[0].id })); }
      if(school.organization_id){const oy=await organizationApi.academicYears(school.organization_id);setOrgYears(oy);const current=oy.find(y=>y.status==="active")||oy[0];setErpYearId(current?.id||"");}
    } catch (err: unknown) { setError(apiErrorMessage(err,"Failed to load fee data")); }
  };
  useEffect(() => { if (schoolId) void load(); }, [schoolId]);
  useEffect(() => { if (selectedCampus) void foundationApi.academicYears(selectedCampus).then(setYears).catch(() => setYears([])); }, [selectedCampus]);
  useEffect(() => { if (selectedCampus) void academicApi.classes(selectedCampus).then(setClasses).catch(() => setClasses([])); }, [selectedCampus]);
  useEffect(() => { if (selectedClass) void academicApi.sections(selectedClass).then(setSections).catch(() => setSections([])); else setSections([]); }, [selectedClass]);
  useEffect(() => { if (studentId) void feeApi.charges(schoolId, studentId).then(setCharges).catch(() => setCharges([])); else setCharges([]); }, [studentId, schoolId]);
  useEffect(()=>{if(!erpYearId||!schoolId)return;erpAccessApi.policy(schoolId,erpYearId).then(p=>{if(p){setErpFeeHeadId(p.fee_head_id);setErpAmount(p.annual_amount);setErpEnabled(p.is_enabled);}else{setErpFeeHeadId("");setErpAmount("");setErpEnabled(true);}}).catch(()=>{});},[erpYearId,schoolId]);

  const createHead = async (e: FormEvent) => { e.preventDefault(); setError(""); try { await feeApi.createHead(schoolId, headForm); setHeadForm({ code: "", name: "", is_misc: false }); setMessage("Fee head created"); await load(); } catch (err: unknown) { setError(apiErrorMessage(err,"Failed to create fee head")); } };
  const createStructure = async (e: FormEvent) => { e.preventDefault(); setError(""); try { await feeApi.createStructure(schoolId, { ...structureForm, academic_class_id: structureForm.academic_class_id || undefined, section_id: structureForm.section_id || undefined, due_date: structureForm.due_date || undefined }); setMessage("Fee structure created"); await load(); } catch (err: unknown) { setError(apiErrorMessage(err,"Failed to create fee structure")); } };
  const saveERPPolicy=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");if(!erpYearId||!erpFeeHeadId||!erpAmount){setError("Academic Year, Fee Head and Annual Amount are required.");return;}try{await erpAccessApi.setPolicy(schoolId,{organization_academic_year_id:erpYearId,fee_head_id:erpFeeHeadId,annual_amount:erpAmount,is_enabled:erpEnabled});setMessage("Parent / Student ERP annual access fee configured.");}catch(err){setError(apiErrorMessage(err,"Failed to configure ERP access fee."));}};
  const collect = async () => { const allocations = Object.entries(payment.amountByCharge).filter(([, amount]) => Number(amount) > 0).map(([charge_id, amount]) => ({ charge_id, amount })); if (!studentId || allocations.length === 0) { setError("Select a student and enter at least one payment allocation"); return; } try { const result = await feeApi.collectPayment(schoolId, { student_id: studentId, payment_mode: payment.mode, upi_reference_last5: payment.mode === "upi" ? payment.upi : undefined, allocations }); setMessage(`Payment posted. Receipt: ${result.receipt_number}`); setPayment({ mode: "cash", upi: "", amountByCharge: {} }); setCharges(await feeApi.charges(schoolId, studentId)); } catch (err: unknown) { setError(apiErrorMessage(err,"Failed to collect payment")); } };

  return <div className="space-y-6">
    <div><h1 className="text-2xl font-bold">Fees Management</h1><p className="text-gray-500 mt-1">Fee setup, yearly Parent / Student ERP access fee, student ledger and collections.</p></div>
    {error && <div className="rounded-lg bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">{error}</div>}
    {message && <div className="rounded-lg bg-green-50 border border-green-200 text-green-700 px-4 py-3 text-sm">{message}</div>}

    {canManageERP&&<section className="card"><h2 className="text-lg font-semibold">Parent / Student ERP Annual Access</h2><p className="text-sm text-gray-500 mt-1 mb-4">Org Admin / School Admin selects the fee head and yearly amount. When Teacher or Accounts opts a Student, access activates immediately and this charge is added once to the yearly ledger.</p><form onSubmit={saveERPPolicy} className="grid grid-cols-1 md:grid-cols-4 gap-4"><Select label="Organization Academic Year" value={erpYearId} options={orgYears.map(y=>[y.id,`${y.name} (${y.status})`])} onChange={setErpYearId}/><Select label="ERP Fee Head" value={erpFeeHeadId} options={heads.map(h=>[h.id,`${h.code} · ${h.name}`])} onChange={setErpFeeHeadId}/><Field label="Annual Amount" value={erpAmount} onChange={setErpAmount} type="number" required/><label className="flex items-end gap-2 pb-2"><input type="checkbox" checked={erpEnabled} onChange={e=>setErpEnabled(e.target.checked)}/><span className="text-sm">Enable ERP access opt-in</span></label><div className="md:col-span-4"><button className="btn-primary">Save ERP Access Fee</button></div></form></section>}

    {canManageHeads && <section className="card"><h2 className="text-lg font-semibold mb-4">Fee Head Setup</h2><form onSubmit={createHead} className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Code" value={headForm.code} onChange={(v) => setHeadForm({ ...headForm, code: v })} required /><Field label="Name" value={headForm.name} onChange={(v) => setHeadForm({ ...headForm, name: v })} required /><div className="flex items-end"><button className="btn-primary">Create Fee Head</button></div></form><div className="mt-4 flex flex-wrap gap-2">{heads.map((h) => <span key={h.id} className="text-xs px-2 py-1 rounded bg-gray-100">{h.code} · {h.name}</span>)}</div></section>}
    {canManageStructures && <section className="card"><h2 className="text-lg font-semibold mb-4">Fee Structure Setup</h2><form onSubmit={createStructure} className="grid grid-cols-1 md:grid-cols-3 gap-4"><Select label="Campus" value={structureForm.campus_id} options={campuses.map((c) => [c.id, c.name])} onChange={(v) => { setSelectedCampus(v); setStructureForm({ ...structureForm, campus_id: v, academic_year_id: "", academic_class_id: "", section_id: "" }); }} /><Select label="Academic year" value={structureForm.academic_year_id} options={years.map((y) => [y.id, y.name || y.code])} onChange={(v) => setStructureForm({ ...structureForm, academic_year_id: v })} /><Select label="Fee head" value={structureForm.fee_head_id} options={heads.map((h) => [h.id, h.name])} onChange={(v) => setStructureForm({ ...structureForm, fee_head_id: v })} /><Select label="Class (optional)" value={structureForm.academic_class_id} options={classes.map((c) => [c.id, c.name])} onChange={(v) => { setSelectedClass(v); setStructureForm({ ...structureForm, academic_class_id: v, section_id: "" }); }} /><Select label="Section (optional)" value={structureForm.section_id} options={sections.map((s) => [s.id, s.name])} onChange={(v) => setStructureForm({ ...structureForm, section_id: v })} /><Field label="Frequency" value={structureForm.frequency} onChange={(v) => setStructureForm({ ...structureForm, frequency: v })} required /><Field label="Amount" value={structureForm.amount} onChange={(v) => setStructureForm({ ...structureForm, amount: v })} type="number" required /><Field label="Due date" value={structureForm.due_date} onChange={(v) => setStructureForm({ ...structureForm, due_date: v })} type="date" /><div className="flex items-end"><button className="btn-primary">Create Structure</button></div></form><div className="mt-4 text-sm text-gray-500">{structures.length} structure(s) configured. Bulk structure imports are under School Administration → Bulk Imports.</div></section>}

    <section className="card"><h2 className="text-lg font-semibold mb-4">Student Charges & Payment</h2><div className="max-w-xl"><Select label="Student" value={studentId} options={students.map((s) => [s.id, `${s.first_name} ${s.last_name || ""} · ${s.admission_number}`])} onChange={setStudentId} /></div>{studentId && <div className="mt-5 space-y-3">{charges.map((c) => <div key={c.id} className="border rounded-lg p-3 flex flex-wrap items-center justify-between gap-3"><div><div className="font-medium">{c.description}</div><div className="text-xs text-gray-500">Due {c.due_date || "—"} · {c.status}</div></div><div className="flex items-center gap-2"><span>₹{c.amount}</span>{canCollect && <input className="input w-32" placeholder="Pay" type="number" min="0" max={c.amount} value={payment.amountByCharge[c.id] || ""} onChange={(e) => setPayment({ ...payment, amountByCharge: { ...payment.amountByCharge, [c.id]: e.target.value } })} />}</div></div>)}{charges.length === 0 && <div className="text-gray-500">No charges found.</div>}{canCollect && charges.length > 0 && <div className="flex flex-wrap items-end gap-3 pt-3"><Select label="Payment mode" value={payment.mode} options={[["cash", "Cash"], ["upi", "UPI"]]} onChange={(v) => setPayment({ ...payment, mode: v })} /><div className="w-40">{payment.mode === "upi" && <Field label="UPI last 5" value={payment.upi} onChange={(v) => setPayment({ ...payment, upi: v })} required />}</div><button className="btn-primary" onClick={() => void collect()}>Collect Payment</button></div>}</div>}</section>
  </div>;
}
function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (v: string) => void; type?: string; required?: boolean }) { return <label><span className="label">{label}</span><input className="input" type={type} value={value} onChange={(e) => onChange(e.target.value)} required={required} /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (v: string) => void }) { return <label className="block"><span className="label">{label}</span><select className="input" value={value} onChange={(e) => onChange(e.target.value)}><option value="">Select…</option>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>; }
