import { FormEvent, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import BulkImportPanel from "../components/BulkImportPanel";
import { FormField as Field, FormSelect as Select, StatusAlert as Alert } from "../components/ui/FormControls";
import { academicApi, foundationApi, importApi, marksApi, studentApi } from "../services/api";
import { useAuthStore } from "../store/authStore";
import { hasPermission } from "../utils/permissions";
import { apiErrorMessage } from "../utils/apiError";
import type { AcademicClass, AcademicYear, Campus, MarkRecord, Section, Student, Subject } from "../types";

export default function MarksPage(){
 const {schoolId=""}=useParams();const user=useAuthStore(s=>s.user);const canEdit=hasPermission(user,"marks.edit"),canFinalize=hasPermission(user,"marks.finalize"),canBulk=hasPermission(user,"marks.bulk_upload");
 const [students,setStudents]=useState<Student[]>([]),[campuses,setCampuses]=useState<Campus[]>([]),[years,setYears]=useState<AcademicYear[]>([]),[classes,setClasses]=useState<AcademicClass[]>([]),[sections,setSections]=useState<Section[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[marks,setMarks]=useState<MarkRecord[]>([]),[error,setError]=useState(""),[msg,setMsg]=useState("");
 const [form,setForm]=useState({campus_id:"",academic_year_id:"",academic_class_id:"",section_id:"",student_id:"",subject_id:"",assessment_name:"Unit Test",max_marks:"100",marks_obtained:"",remarks:""});
 const loadBase=async()=>{try{const[ss,mm,cs]=await Promise.all([studentApi.list(schoolId),marksApi.list(schoolId),foundationApi.campuses(schoolId)]);setStudents(ss);setMarks(mm);setCampuses(cs);const campusId=user?.campus_id||form.campus_id||cs[0]?.id||"";if(campusId)await selectCampus(campusId,ss);}catch(e){setError(apiErrorMessage(e,"Failed to load marks data"));}};
 const selectCampus=async(id:string,knownStudents=students)=>{const scopedStudents=knownStudents.filter(s=>s.campus_id===id);setForm(f=>({...f,campus_id:id,academic_year_id:"",academic_class_id:"",section_id:"",subject_id:"",student_id:scopedStudents[0]?.id||""}));if(!id)return;try{const[ys,cls,subs]=await Promise.all([foundationApi.academicYears(id),academicApi.classes(id),academicApi.subjects(id)]);setYears(ys);setClasses(cls);setSubjects(subs);const classId=cls[0]?.id||"";const ss=classId?await academicApi.sections(classId):[];setSections(ss);setForm(f=>({...f,campus_id:id,academic_year_id:ys.find(y=>y.status==="active")?.id||ys[0]?.id||"",academic_class_id:classId,section_id:ss[0]?.id||"",subject_id:subs[0]?.id||"",student_id:scopedStudents[0]?.id||""}));}catch(e){setError(apiErrorMessage(e,"Failed to load marks academic setup"));}};
 useEffect(()=>{if(schoolId)void loadBase()},[schoolId,user?.campus_id]);
 const classChanged=async(id:string)=>{setForm({...form,academic_class_id:id,section_id:""});try{const ss=await academicApi.sections(id);setSections(ss);setForm(f=>({...f,academic_class_id:id,section_id:ss[0]?.id||""}));}catch{setSections([])}};
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setMsg("");try{await marksApi.upsert(schoolId,{academic_year_id:form.academic_year_id,student_id:form.student_id,subject_id:form.subject_id,assessment_name:form.assessment_name,max_marks:Number(form.max_marks),marks_obtained:Number(form.marks_obtained),remarks:form.remarks||null});setMsg("Marks saved and audit logged.");setForm(f=>({...f,marks_obtained:"",remarks:""}));await loadBase()}catch(e){setError(apiErrorMessage(e,"Failed to save marks"));}};
 const bulkContext={campus_id:form.campus_id,academic_year_id:form.academic_year_id,academic_class_id:form.academic_class_id,section_id:form.section_id,subject_id:form.subject_id,assessment_name:form.assessment_name,max_marks:form.max_marks};
 const campusStudents=students.filter(s=>!form.campus_id||s.campus_id===form.campus_id);
 const visibleMarks=marks.filter(m=>!form.campus_id||m.campus_id===form.campus_id);
 const studentName=(id:string)=>{const s=students.find(x=>x.id===id);return s?`${s.first_name} ${s.last_name||""}`:id};const subjectName=(id:string)=>subjects.find(s=>s.id===id)?.name||id;
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Marks</h1><p className="text-gray-500 mt-1">Secure marks entry, finalization and template-driven bulk upload.</p></div>{error&&<Alert kind="error" text={error}/>} {msg&&<Alert kind="success" text={msg}/>} 
 <section className="card grid grid-cols-1 md:grid-cols-4 gap-3"><Select label="Campus" value={form.campus_id} onChange={v=>void selectCampus(v)} options={campuses.map(c=>[c.id,c.name])}/><Select label="Academic Year" value={form.academic_year_id} onChange={v=>setForm({...form,academic_year_id:v})} options={years.map(y=>[y.id,`${y.name} (${y.status})`])}/><Select label="Class" value={form.academic_class_id} onChange={v=>void classChanged(v)} options={classes.map(c=>[c.id,c.name])}/><Select label="Section" value={form.section_id} onChange={v=>setForm({...form,section_id:v})} options={sections.map(s=>[s.id,s.name])}/><Select label="Subject" value={form.subject_id} onChange={v=>setForm({...form,subject_id:v})} options={subjects.map(s=>[s.id,s.name])}/><Field label="Assessment" value={form.assessment_name} onChange={v=>setForm({...form,assessment_name:v})}/><Field label="Maximum Marks" type="number" value={form.max_marks} onChange={v=>setForm({...form,max_marks:v})}/></section>
 {canEdit&&<form onSubmit={submit} className="card grid grid-cols-1 md:grid-cols-3 gap-4"><Select label="Student" value={form.student_id} onChange={v=>setForm({...form,student_id:v})} options={campusStudents.map(x=>[x.id,`${x.first_name} ${x.last_name||""} (${x.admission_number})`])}/><Field label="Marks Obtained" type="number" value={form.marks_obtained} onChange={v=>setForm({...form,marks_obtained:v})}/><Field label="Remarks" value={form.remarks} onChange={v=>setForm({...form,remarks:v})} required={false}/><div className="md:col-span-3"><button className="btn-primary">Save Marks</button></div></form>}
 {canBulk&&<BulkImportPanel title="Bulk Upload Marks" description="Choose Academic Year, Class, Section, Subject, Assessment and Maximum Marks above. The generated template is prefilled with enrolled students." contextReady={Object.values(bulkContext).every(Boolean)&&Number(form.max_marks)>0} templateFilename="marks-import.xlsx" downloadTemplate={()=>importApi.marksTemplate(schoolId,bulkContext)} previewImport={file=>importApi.previewMarks(schoolId,file,bulkContext)} confirmImport={(file,sha)=>importApi.confirmMarks(schoolId,file,sha,bulkContext)} onImported={loadBase}/>} 
 <section className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="py-2">Student</th><th>Subject</th><th>Assessment</th><th>Marks</th><th>Status</th><th></th></tr></thead><tbody>{visibleMarks.map(m=><tr key={m.id} className="border-b last:border-0"><td className="py-3">{studentName(m.student_id)}</td><td>{subjectName(m.subject_id)}</td><td>{m.assessment_name}</td><td>{m.marks_obtained} / {m.max_marks}</td><td>{m.is_locked?"Finalized":"Editable"}</td><td>{canFinalize&&<button className="btn-secondary" onClick={async()=>{try{if(m.is_locked){const reason=(window.prompt("Reason for reopening finalized marks (required):")||"").trim();if(reason.length<3){setError("A reason is required to reopen finalized marks.");return;}await marksApi.lock(schoolId,m.id,false,reason);setMsg("Finalized marks reopened for correction and audit logged.");}else{await marksApi.lock(schoolId,m.id,true);setMsg("Marks finalized and audit logged.");}await loadBase()}catch(e){setError(apiErrorMessage(e,"Failed to change marks finalization status"))}}}>{m.is_locked?"Reopen":"Finalize"}</button>}</td></tr>)}</tbody></table>{visibleMarks.length===0&&<div className="py-8 text-center text-gray-500">No marks entered yet.</div>}</section></div>;
}
