import { FormEvent, useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { IndianRupee, ReceiptText, Search, SlidersHorizontal, WalletCards } from "lucide-react";
import { platformPaymentsApi, subscriptionApi } from "../services/api";
import type { OrganizationSubscription, PaymentSummary, SubscriptionPayment } from "../types";
import { apiErrorMessage } from "../utils/apiError";

const money=(value?:string)=>`₹${Number(value||0).toLocaleString("en-IN",{minimumFractionDigits:2})}`;
type Tab="collection"|"details"|"receipts"|"financial";
const tabs:{id:Tab;label:string}[]=[{id:"collection",label:"Payment Collection"},{id:"details",label:"Payment Details"},{id:"receipts",label:"Receipts"},{id:"financial",label:"Financial Details"}];
const isTab=(value:string|null):value is Tab=>value==="collection"||value==="details"||value==="receipts"||value==="financial";

export default function PaymentsPage(){
 const[params]=useSearchParams(); const requestedTab=params.get("tab"); const organizationFilter=params.get("organization")||"";
 const [tab,setTab]=useState<Tab>(isTab(requestedTab)?requestedTab:"collection"),[summary,setSummary]=useState<PaymentSummary|null>(null),[accounts,setAccounts]=useState<OrganizationSubscription[]>([]),[receipts,setReceipts]=useState<SubscriptionPayment[]>([]),[error,setError]=useState(""),[paying,setPaying]=useState<OrganizationSubscription|null>(null),[form,setForm]=useState({amount:"",payment_mode:"bank_transfer",reference_number:"",notes:""}),[billing,setBilling]=useState({legal_name:"School ERP",billing_address:"",gstin:"",default_tax_mode:"non_gst",default_tax_rate:"0",gst_type:"cgst_sgst",receipt_prefix:"ERP-RCPT",payment_instructions:""});
 const [receiptFilters,setReceiptFilters]=useState({search:"",mode:"all",status:"all",from:"",to:""});
 useEffect(()=>{if(isTab(requestedTab))setTab(requestedTab)},[requestedTab]);
 const load=async()=>{try{const[s,a,r,b]=await Promise.all([platformPaymentsApi.summary(),platformPaymentsApi.details(),platformPaymentsApi.receipts(),platformPaymentsApi.settings()]);setSummary(s);setAccounts(a);setReceipts(r);setBilling(prev=>({...prev,...b,default_tax_rate:String(b.default_tax_rate)}));}catch(e){setError(apiErrorMessage(e,"Unable to load platform payments."));}};
 useEffect(()=>{void load();},[]);
 const visibleAccounts=organizationFilter?accounts.filter(a=>a.organization_id===organizationFilter):accounts;
 const accountById=useMemo(()=>Object.fromEntries(accounts.map(a=>[a.id,a])),[accounts]);
 const collectionAccounts=visibleAccounts.filter(a=>a.billing_cycle!=="trial"&&Number(a.balance_amount)>0);
 const paidAccounts=visibleAccounts.filter(a=>Number(a.balance_amount)<=0&&a.billing_cycle!=="trial").length;
 const overdueAccounts=visibleAccounts.filter(a=>a.payment_status==="overdue").length;
 const collectionProgress=Number(summary?.total_finalized||0)>0?Math.round((Number(summary?.total_received||0)/Number(summary?.total_finalized||0))*100):0;
 const filteredReceipts=receipts.filter(r=>{const account=accountById[r.organization_subscription_id];const haystack=[r.receipt_number,r.payment_mode,r.reference_number||"",account?.organization_name||"",account?.plan_name||""].join(" ").toLowerCase();const paidStatus=Number(r.amount)>0?"paid":"adjustment";const day=new Date(r.payment_date).toISOString().slice(0,10);return (!receiptFilters.search||haystack.includes(receiptFilters.search.toLowerCase()))&&(receiptFilters.mode==="all"||r.payment_mode===receiptFilters.mode)&&(receiptFilters.status==="all"||paidStatus===receiptFilters.status)&&(!receiptFilters.from||day>=receiptFilters.from)&&(!receiptFilters.to||day<=receiptFilters.to);});
 const pay=async(e:FormEvent)=>{e.preventDefault();if(!paying)return;setError("");try{await platformPaymentsApi.record(paying.id,form);setPaying(null);setForm({amount:"",payment_mode:"bank_transfer",reference_number:"",notes:""});await load();}catch(err){setError(apiErrorMessage(err,"Payment could not be recorded."));}};
 const editTerms=async(a:OrganizationSubscription)=>{const count=window.prompt("Agreed number of schools",String(a.school_count));if(count===null)return;const value=window.prompt("Minimum payment required before school activation",a.activation_minimum_amount);if(value===null)return;try{await subscriptionApi.updateAccount(a.id,{school_count:Number(count),activation_minimum_amount:value});await load();}catch(e){setError(apiErrorMessage(e,"Agreed terms could not be updated."));}};
 const saveBilling=async(e:FormEvent)=>{e.preventDefault();try{await platformPaymentsApi.updateSettings(billing);await load();}catch(err){setError(apiErrorMessage(err,"Receipt settings could not be saved."));}};
 const printReceipt=async(id:string)=>{try{const r=await platformPaymentsApi.receipt(id);const w=window.open("","receipt");if(!w)return;w.document.title=`Receipt ${r.receipt_number}`;const heading=w.document.createElement("h1");heading.textContent=r.issuer.legal_name;const details=w.document.createElement("pre");details.textContent=`Payment Receipt ${r.receipt_number}\nOrganization: ${r.organization_name} (${r.organization_code})\nPlan: ${r.plan_name} · ${r.billing_cycle}\nAmount received: ₹${r.amount_received}\nFinalized: ₹${r.finalized_amount}\nTotal received: ₹${r.total_received}\nBalance: ₹${r.balance_amount}\nTax: ${r.tax_mode} ${r.tax_rate}% · ₹${r.tax_amount}\nDate: ${new Date(r.payment_date).toLocaleString()} · Mode: ${r.payment_mode}`;w.document.body.replaceChildren(heading,details);w.print();}catch(e){setError(apiErrorMessage(e,"Receipt could not be opened."));}};
 const openStatement=async(id:string)=>{try{const data=await platformPaymentsApi.statement(id);const w=window.open("","statement");if(!w)return;w.document.title="Subscription Statement";const heading=w.document.createElement("h1");heading.textContent="Subscription Statement";const details=w.document.createElement("pre");details.textContent=JSON.stringify(data,null,2);w.document.body.replaceChildren(heading,details);}catch(e){setError(apiErrorMessage(e,"Statement could not be opened."));}};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Payments</h1><p className="mt-1 text-gray-500">Collect subscription payments, review account balances, search receipts and maintain platform financial settings.</p></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{[["Finalized",summary?.total_finalized],["Received",summary?.total_received],["Outstanding",summary?.outstanding],["Overdue",summary?.overdue],["This Month",summary?.current_month_collection]].map(([label,value])=><div className="card" key={label}><IndianRupee className="text-primary-700"/><p className="mt-2 text-sm text-gray-500">{label}</p><p className="text-xl font-bold">{money(value)}</p></div>)}</div>
 <div className="flex flex-wrap gap-2 border-b">{tabs.map(item=><button key={item.id} onClick={()=>setTab(item.id)} className={`px-4 py-3 text-sm font-semibold ${tab===item.id?"border-b-2 border-primary-600 text-primary-700":"text-gray-500"}`}>{item.label}</button>)}</div>
 {paying&&<form onSubmit={pay} className="card border-primary-200"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Record Payment</h2><p className="text-sm text-gray-500">{paying.organization_name} · Balance {money(paying.balance_amount)} · Minimum activation {money(paying.activation_minimum_amount)}</p></div><button type="button" className="btn-secondary" onClick={()=>setPaying(null)}>Cancel</button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><Field label="Amount" value={form.amount} type="number" onChange={v=>setForm({...form,amount:v})}/><label><span className="label">Payment Mode</span><select className="input" value={form.payment_mode} onChange={e=>setForm({...form,payment_mode:e.target.value})}><option value="bank_transfer">Bank Transfer</option><option value="upi">UPI</option><option value="cash">Cash</option><option value="card">Card</option><option value="cheque">Cheque</option><option value="other">Other</option></select></label><Field label="Reference Number" value={form.reference_number} required={false} onChange={v=>setForm({...form,reference_number:v})}/><Field label="Notes" value={form.notes} required={false} onChange={v=>setForm({...form,notes:v})}/></div><button className="btn-primary mt-4">Record and Generate Receipt</button></form>}
 {tab==="collection"&&<><section className="grid gap-4 md:grid-cols-3"><Insight title="Ready to Collect" value={String(collectionAccounts.length)} note="Accounts with pending paid-plan balance"/><Insight title="Paid Accounts" value={String(paidAccounts)} note="Organizations with no balance"/><Insight title="Collection Progress" value={`${collectionProgress}%`} note="Received against finalized amount"/></section><AccountsTable title="Payment Collection" subtitle="Use this workspace to collect subscription payments and generate receipts." accounts={collectionAccounts} empty="No pending paid-plan collections found." action={a=><button className="btn-primary text-xs" onClick={()=>{setPaying(a);setForm({...form,amount:a.balance_amount});}}>Collect Payment</button>}/></>}
 {tab==="details"&&<><section className="grid gap-4 md:grid-cols-3"><Insight title="Billing Accounts" value={String(visibleAccounts.length)} note="Organizations with subscription accounts"/><Insight title="Outstanding Balance" value={money(summary?.outstanding)} note={`${overdueAccounts} overdue account${overdueAccounts===1?"":"s"}`}/><Insight title="Current Month" value={money(summary?.current_month_collection)} note="Collection booked this month"/></section><AccountsTable title="Billing Overview" subtitle="Read-only subscription payment details with plan, cycle, due amount and payment status." accounts={visibleAccounts} action={a=><div className="flex gap-2">{Number(a.total_received)===0&&a.billing_cycle!=="trial"&&<button className="btn-secondary text-xs" onClick={()=>void editTerms(a)}>Edit Terms</button>}<button className="btn-secondary text-xs" onClick={()=>{setTab("collection");setPaying(a);setForm({...form,amount:a.balance_amount});}}>Collect</button></div>}/></>}
 {tab==="receipts"&&<section className="card overflow-x-auto"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><ReceiptText/><div><h2 className="font-semibold">Payment Receipts</h2><p className="text-sm text-gray-500">Filter receipts by receipt number, organization, payment mode, status and date.</p></div></div><span className="text-sm font-semibold text-gray-600">{filteredReceipts.length} results</span></div><div className="mb-4 grid gap-3 md:grid-cols-5"><label className="md:col-span-2"><span className="label">Search</span><div className="relative"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-gray-400"/><input className="input pl-9" value={receiptFilters.search} placeholder="Receipt, organization, reference" onChange={e=>setReceiptFilters({...receiptFilters,search:e.target.value})}/></div></label><label><span className="label">Mode</span><select className="input" value={receiptFilters.mode} onChange={e=>setReceiptFilters({...receiptFilters,mode:e.target.value})}><option value="all">All Modes</option><option value="bank_transfer">Bank Transfer</option><option value="upi">UPI</option><option value="cash">Cash</option><option value="card">Card</option><option value="cheque">Cheque</option><option value="other">Other</option></select></label><label><span className="label">Status</span><select className="input" value={receiptFilters.status} onChange={e=>setReceiptFilters({...receiptFilters,status:e.target.value})}><option value="all">All Status</option><option value="paid">Paid</option><option value="adjustment">Adjustment</option></select></label><label><span className="label">From</span><input className="input" type="date" value={receiptFilters.from} onChange={e=>setReceiptFilters({...receiptFilters,from:e.target.value})}/></label><label><span className="label">To</span><input className="input" type="date" value={receiptFilters.to} onChange={e=>setReceiptFilters({...receiptFilters,to:e.target.value})}/></label></div><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-gray-500"><th className="py-2">Receipt</th><th>Organization</th><th>Date</th><th>Mode</th><th>Reference</th><th>Amount</th><th>Action</th></tr></thead><tbody>{filteredReceipts.map(r=>{const account=accountById[r.organization_subscription_id];return <tr key={r.id} className="border-b"><td className="py-3 font-mono">{r.receipt_number}</td><td>{account?.organization_name||"-"}</td><td>{new Date(r.payment_date).toLocaleDateString()}</td><td className="capitalize">{r.payment_mode.replace(/_/g," ")}</td><td>{r.reference_number||"-"}</td><td className="font-semibold text-green-700">{money(r.amount)}</td><td><button className="btn-secondary text-xs" onClick={()=>void printReceipt(r.id)}>Print Receipt</button></td></tr>})}</tbody></table>{filteredReceipts.length===0&&<p className="py-6 text-center text-sm text-gray-500">No receipts match the selected filters.</p>}</section>}
 {tab==="financial"&&<><section className="grid gap-4 md:grid-cols-3"><Insight title="Financial Control Center" value={money(summary?.total_finalized)} note="Total finalized billing value"/><Insight title="Receipts Issued" value={String(receipts.length)} note="Receipts available for audit"/><Insight title="Balance Exposure" value={money(summary?.outstanding)} note="Pending collection across accounts"/></section><form className="card" onSubmit={saveBilling}><div className="flex items-center gap-2"><SlidersHorizontal/><h2 className="font-semibold">Receipt and Tax Configuration</h2></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Field label="Legal Name" value={billing.legal_name} onChange={v=>setBilling({...billing,legal_name:v})}/><label><span className="label">Default Tax Format</span><select className="input" value={billing.default_tax_mode} onChange={e=>setBilling({...billing,default_tax_mode:e.target.value})}><option value="non_gst">Non-GST</option><option value="gst">GST</option></select></label><Field label="GST Rate" type="number" value={billing.default_tax_rate} onChange={v=>setBilling({...billing,default_tax_rate:v})}/><Field label="GSTIN" required={false} value={billing.gstin||""} onChange={v=>setBilling({...billing,gstin:v})}/><Field label="Receipt Prefix" value={billing.receipt_prefix} onChange={v=>setBilling({...billing,receipt_prefix:v})}/><Field label="Billing Address" required={false} value={billing.billing_address||""} onChange={v=>setBilling({...billing,billing_address:v})}/></div><button className="btn-primary mt-4">Save Receipt Settings</button></form><AccountsTable title="Statement Summary" subtitle="Open consolidated statements for any organization subscription account." accounts={visibleAccounts} action={a=><button className="btn-secondary text-xs" onClick={()=>void openStatement(a.id)}>View Statement</button>}/></>}
 </div>;
}
function Insight({title,value,note}:{title:string;value:string;note:string}){return <div className="card"><p className="text-sm font-medium text-gray-500">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-gray-500">{note}</p></div>}
function AccountsTable({accounts,action,title,subtitle,empty="No organization accounts found."}:{accounts:OrganizationSubscription[];action:(a:OrganizationSubscription)=>React.ReactNode;title:string;subtitle?:string;empty?:string}){return <section className="card overflow-x-auto"><div className="mb-4 flex gap-2"><WalletCards/><div><h2 className="font-semibold">{title}</h2>{subtitle&&<p className="text-sm text-gray-500">{subtitle}</p>}</div></div><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-gray-500"><th className="py-2">Organization</th><th>Plan</th><th>Cycle</th><th>Finalized</th><th>Received</th><th>Balance</th><th>Status</th><th>Actions</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-b"><td className="py-3"><p className="font-medium">{a.organization_name}</p><p className="text-xs text-gray-500">{a.school_count} schools</p></td><td>{a.plan_name}</td><td className="capitalize">{a.billing_cycle.replace(/_/g," ")}</td><td>{money(a.finalized_amount)}</td><td>{money(a.total_received)}</td><td className={Number(a.balance_amount)>0?"font-semibold text-amber-700":"font-semibold text-green-700"}>{money(a.balance_amount)}</td><td><span className="rounded-full bg-gray-100 px-2 py-1 text-xs capitalize">{a.payment_status.replace(/_/g," ")}</span></td><td>{action(a)}</td></tr>)}</tbody></table>{accounts.length===0&&<p className="py-6 text-center text-sm text-gray-500">{empty}</p>}</section>}
function Field({label,value,onChange,type="text",required=true}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label><span className="label">{label}{required?" *":""}</span><input className="input" type={type} step={type==="number"?"0.01":undefined} min={type==="number"?"0":undefined} required={required} value={value} onChange={e=>onChange(e.target.value)}/></label>}