import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { rbacApi, schoolApi } from "../services/api";
import { useAuthStore } from "../store/authStore";
import type { RbacPermission, RbacRole, School } from "../types";
import { apiErrorMessage } from "../utils/apiError";

export default function RolesPermissionsPage(){
  const { schoolId = "" } = useParams(); const user = useAuthStore(s=>s.user);
  const [school,setSchool]=useState<School|null>(null),[roles,setRoles]=useState<RbacRole[]>([]),[permissions,setPermissions]=useState<RbacPermission[]>([]),[selected,setSelected]=useState(""),[draft,setDraft]=useState<Set<string>>(new Set());
  const [error,setError]=useState(""),[notice,setNotice]=useState(""),[saving,setSaving]=useState(false),[showCreate,setShowCreate]=useState(false);
  const [newRole,setNewRole]=useState({code:"",name:"",description:""}); const [newPerms,setNewPerms]=useState<Set<string>>(new Set());
  const load=async()=>{if(!schoolId)return;setError("");try{const[s,rs,ps]=await Promise.all([schoolApi.get(schoolId),rbacApi.roles(schoolId),rbacApi.permissions()]);setSchool(s);setRoles(rs);setPermissions(ps);const keep=rs.find(r=>r.id===selected)||rs[0];if(keep){setSelected(keep.id);setDraft(new Set(keep.permissions));}}catch(e){setError(apiErrorMessage(e,"Failed to load roles and permissions"));}};
  useEffect(()=>{void load();},[schoolId]);
  const role=roles.find(r=>r.id===selected);
  const grouped=useMemo(()=>{const out:Record<string,RbacPermission[]>={};for(const p of permissions)(out[p.module] ||= []).push(p);return out;},[permissions]);
  const choose=(id:string)=>{setSelected(id);const r=roles.find(x=>x.id===id);setDraft(new Set(r?.permissions||[]));setError("");setNotice("");};
  const toggle=(code:string)=>setDraft(prev=>{const n=new Set(prev);n.has(code)?n.delete(code):n.add(code);return n;});
  const toggleNew=(code:string)=>setNewPerms(prev=>{const n=new Set(prev);n.has(code)?n.delete(code):n.add(code);return n;});
  const save=async()=>{if(!role||!user?.is_superuser||role.is_system)return;setSaving(true);setError("");setNotice("");try{const updated=await rbacApi.updatePermissions(role.id,[...draft]);setRoles(rs=>rs.map(r=>r.id===updated.id?updated:r));setDraft(new Set(updated.permissions));setNotice("Custom permission profile updated.");}catch(e){setError(apiErrorMessage(e,"Failed to update custom role permissions"));}finally{setSaving(false);}};
  const create=async(e:FormEvent)=>{e.preventDefault();if(!school?.organization_id)return;setSaving(true);setError("");setNotice("");try{const created=await rbacApi.createRole({code:newRole.code.trim(),name:newRole.name.trim(),description:newRole.description.trim()||null,organization_id:school.organization_id,school_id:schoolId,permission_codes:[...newPerms]});setNewRole({code:"",name:"",description:""});setNewPerms(new Set());setShowCreate(false);await load();setSelected(created.id);setDraft(new Set(created.permissions));setNotice("Custom role created. It can now be assigned by Super Admin to a user.");}catch(e){setError(apiErrorMessage(e,"Failed to create custom role"));}finally{setSaving(false);}};
  return <div className="space-y-6">
    <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Roles & Permissions</h1><p className="text-gray-500 mt-1">{school?.configuration?.name||school?.code||"School"} · predefined user types are protected; Super Admin can add custom permission profiles.</p></div>{user?.is_superuser&&<button className="btn-primary" onClick={()=>setShowCreate(!showCreate)}>New Custom Role</button>}</div>
    {error&&<div className="rounded-lg bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">{error}</div>}{notice&&<div className="rounded-lg bg-green-50 border border-green-200 text-green-800 px-4 py-3 text-sm">{notice}</div>}
    {showCreate&&<form className="card space-y-4" onSubmit={create}><div><h2 className="text-lg font-semibold">Create Custom Permission Profile</h2><p className="text-sm text-gray-500">Only Super Admin can create or change custom profiles. Platform-only permissions are rejected by the backend.</p></div><div className="grid md:grid-cols-3 gap-4"><Field label="Role Code" value={newRole.code} onChange={v=>setNewRole({...newRole,code:v})}/><Field label="Role Name" value={newRole.name} onChange={v=>setNewRole({...newRole,name:v})}/><Field label="Description" value={newRole.description} onChange={v=>setNewRole({...newRole,description:v})} required={false}/></div><PermissionGrid grouped={grouped} selected={newPerms} disabled={false} onToggle={toggleNew}/><div className="flex gap-2"><button className="btn-primary" disabled={saving}>{saving?"Creating…":"Create Custom Role"}</button><button type="button" className="btn-secondary" onClick={()=>setShowCreate(false)}>Cancel</button></div></form>}
    <div className="grid grid-cols-1 xl:grid-cols-[280px_1fr] gap-5"><section className="card p-0 overflow-hidden"><div className="px-4 py-3 border-b font-semibold">Role Profiles</div>{roles.map(r=><button key={r.id} onClick={()=>choose(r.id)} className={`w-full text-left px-4 py-3 border-b last:border-0 ${selected===r.id?"bg-primary-50 text-primary-800":"hover:bg-gray-50"}`}><div className="font-medium">{r.name}</div><div className="text-xs text-gray-400 font-mono">{r.code} · {r.is_system?"Predefined":"Custom"}</div></button>)}</section>
      <section className="card"><div className="flex flex-wrap items-center justify-between gap-3 mb-5"><div><h2 className="text-lg font-semibold">{role?.name||"Select a role"}</h2><p className="text-sm text-gray-500">{role?.is_system?"Predefined user-type permission matrix — protected from ad-hoc editing.":"Custom Super Admin permission profile."}</p></div>{user?.is_superuser&&role&&!role.is_system&&<button className="btn-primary" disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save Custom Permissions"}</button>}</div>{role?.is_system&&<div className="mb-4 rounded-lg bg-blue-50 border border-blue-200 text-blue-800 px-4 py-3 text-sm">Predefined role permissions are controlled by the ERP release baseline. Create a custom role when an exceptional user needs different access.</div>}<PermissionGrid grouped={grouped} selected={draft} disabled={!user?.is_superuser||!role||!!role.is_system} onToggle={toggle}/></section>
    </div>
  </div>;
}
function PermissionGrid({grouped,selected,disabled,onToggle}:{grouped:Record<string,RbacPermission[]>;selected:Set<string>;disabled:boolean;onToggle:(code:string)=>void}){return <div className="space-y-5">{Object.entries(grouped).map(([module,ps])=><div key={module}><h3 className="font-semibold capitalize mb-2">{module.replace(/_/g," ")}</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-2">{ps.map(p=><label key={p.id} className="flex items-start gap-3 border rounded-lg p-3"><input type="checkbox" className="mt-1" checked={selected.has(p.code)} disabled={disabled} onChange={()=>onToggle(p.code)}/><div><div className="text-sm font-medium">{p.name}</div><div className="text-xs text-gray-400 font-mono">{p.code}</div></div></label>)}</div></div>)}</div>}
function Field({label,value,onChange,required=true}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label><span className="label">{label}</span><input className="input" required={required} value={value} onChange={e=>onChange(e.target.value)}/></label>}
