import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { schoolApi } from "../services/api";
import { useAuthStore } from "../store/authStore";
import { hasModule, hasPermission } from "../utils/permissions";
import type { School, SchoolConfiguration, SchoolLicense, SchoolUDISE } from "../types";
import { apiErrorMessage } from "../utils/apiError";

export default function SchoolDetailPage(){
 const {schoolId=""}=useParams(); const navigate=useNavigate(); const user=useAuthStore(s=>s.user);
 const canEdit=!!user&&(user.is_superuser||["ORGANIZATION_ADMIN","SCHOOL_ADMIN"].includes(user.account_type))&&hasPermission(user,"school.config.edit");
 const canViewLicense=!!user&&(user.is_superuser||hasPermission(user,"license.view"));
 const canManageLifecycle=!!user&&(user.is_superuser||user.account_type==="ORGANIZATION_ADMIN");
 const [school,setSchool]=useState<School|null>(null); const [license,setLicense]=useState<SchoolLicense|null>(null); const [editing,setEditing]=useState(false);
 const [form,setForm]=useState<Partial<SchoolConfiguration>>({}); const [udise,setUdise]=useState<SchoolUDISE[]>([]); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 const load=async()=>{if(!schoolId)return;try{const s=await schoolApi.get(schoolId);setSchool(s);setForm(s.configuration||{});setUdise((s.udise_codes||[]).filter(x=>x.is_active!==false));setLicense(canViewLicense?await schoolApi.getLicense(schoolId):null);}catch(e){setError(apiErrorMessage(e,"Failed to load School details"));}};
 useEffect(()=>{void load();},[schoolId,canViewLicense]);
 const save=async()=>{if(!schoolId||!canEdit)return;setSaving(true);setError("");try{const updated=await schoolApi.updateProfile(schoolId,{configuration:{name:form.name,short_name:form.short_name,area:form.area,tagline:form.tagline,principal_head_name:form.principal_head_name,principal_head_email:form.principal_head_email||null,principal_head_phone:form.principal_head_phone,logo_url:form.logo_url,address_line1:form.address_line1,address_line2:form.address_line2,city:form.city,state:form.state,country:form.country,pincode:form.pincode,phone:form.phone,email:form.email||null,website:form.website,board:form.board},udise_codes:udise.filter(x=>x.udise_code.trim()).map(x=>({udise_code:x.udise_code.trim(),label:x.label||null,is_primary:x.is_primary}))});setSchool(updated);setForm(updated.configuration||{});setUdise(updated.udise_codes||[]);setEditing(false);}catch(e){setError(apiErrorMessage(e,"Failed to save School profile"));}finally{setSaving(false);}};
 const toggle=async()=>{if(!school||!canManageLifecycle)return;try{await schoolApi.setStatus(school.id,!school.is_active);await load();}catch(e){setError(apiErrorMessage(e,"Failed to update School status"));}};
 const archive=async()=>{if(!school||!canManageLifecycle)return;if(school.is_active){setError("Disable the School before archiving it.");return;}try{await schoolApi.archive(school.id);navigate('/schools');}catch(e){setError(apiErrorMessage(e,"Failed to archive School"));}};
 const updateUdise=(i:number,patch:Partial<SchoolUDISE>)=>setUdise(rows=>rows.map((r,j)=>j===i?{...r,...patch}:patch.is_primary?{...r,is_primary:false}:r));
 if(!school)return <div className="text-gray-500">{error||"Loading School…"}</div>; const c=school.configuration;
 return <div className="space-y-6">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">{c?.name||school.code}</h1><p className="text-gray-500 mt-1">ERP School Code: <span className="font-mono font-semibold">{school.code}</span> · permanent business identifier</p></div><div className="flex flex-wrap gap-2">{user?.is_superuser&&<Link className="btn-secondary" to={`/schools/${schoolId}/modules`}>Modules</Link>}{hasPermission(user,"user.view")&&<Link className="btn-secondary" to={`/schools/${schoolId}/users`}>Users</Link>}{hasPermission(user,"academic_year.view")&&<Link className="btn-secondary" to={`/schools/${schoolId}/academic-years`}>Academic Years</Link>}{hasPermission(user,"student.view")&&hasModule(user,"student")&&<Link className="btn-secondary" to={`/schools/${schoolId}/students`}>Students</Link>}{hasPermission(user,"teacher.view")&&hasModule(user,"teacher")&&<Link className="btn-secondary" to={`/schools/${schoolId}/teachers`}>Teachers</Link>}{hasPermission(user,"fee.view")&&hasModule(user,"fee")&&<Link className="btn-secondary" to={`/schools/${schoolId}/fees`}>Fees</Link>}{hasPermission(user,"audit.view")&&<Link className="btn-secondary" to={`/schools/${schoolId}/audit`}>Audit</Link>}{canManageLifecycle&&<button className="btn-secondary" onClick={()=>void toggle()}>{school.is_active?"Disable":"Enable"}</button>}{canManageLifecycle&&!school.is_active&&<button className="btn-secondary text-red-700" onClick={()=>void archive()}>Archive School</button>}</div></div>
  {error&&<div className="rounded-lg bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm">{error}</div>}
  <section className="card"><div className="flex items-start justify-between gap-3 mb-5"><div><h2 className="text-lg font-semibold">School / Branch Profile</h2><p className="text-sm text-gray-500 mt-1">The information entered at School creation is maintained here. There is no separate School Configuration module.</p></div>{canEdit&&!editing&&<button className="btn-secondary" onClick={()=>setEditing(true)}>Correct / Edit</button>}</div>
   {editing?<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
    <Field label="School Name" value={form.name||""} onChange={v=>setForm({...form,name:v})}/><Field label="Short Name" value={form.short_name||""} onChange={v=>setForm({...form,short_name:v})}/><Field label="Area / Village" value={form.area||""} onChange={v=>setForm({...form,area:v})}/><label><span className="label">Area Code</span><input className="input bg-gray-100" value={form.area_code||""} disabled/><span className="text-xs text-gray-500">Locked after creation with ERP School Code.</span></label><Field label="Tagline" value={form.tagline||""} onChange={v=>setForm({...form,tagline:v})}/><Field label="Logo URL" value={form.logo_url||""} onChange={v=>setForm({...form,logo_url:v})}/><Field label="Principal / Head" value={form.principal_head_name||""} onChange={v=>setForm({...form,principal_head_name:v})}/><Field label="Principal Email" value={form.principal_head_email||""} onChange={v=>setForm({...form,principal_head_email:v})}/><Field label="Principal Phone" value={form.principal_head_phone||""} onChange={v=>setForm({...form,principal_head_phone:v})}/><Field label="Address Line 1" value={form.address_line1||""} onChange={v=>setForm({...form,address_line1:v})}/><Field label="Address Line 2" value={form.address_line2||""} onChange={v=>setForm({...form,address_line2:v})}/><Field label="City" value={form.city||""} onChange={v=>setForm({...form,city:v})}/><Field label="State" value={form.state||""} onChange={v=>setForm({...form,state:v})}/><Field label="PIN" value={form.pincode||""} onChange={v=>setForm({...form,pincode:v})}/><Field label="School Phone" value={form.phone||""} onChange={v=>setForm({...form,phone:v})}/><Field label="School Email" value={form.email||""} onChange={v=>setForm({...form,email:v})}/><Field label="Website" value={form.website||""} onChange={v=>setForm({...form,website:v})}/>
    <div className="md:col-span-2 border-t pt-4"><div className="flex justify-between"><h3 className="font-semibold">UDISE Codes (Optional)</h3><button type="button" className="btn-secondary text-xs" onClick={()=>setUdise([...udise,{udise_code:"",label:"",is_primary:udise.length===0}])}>+ Add UDISE</button></div><div className="space-y-2 mt-3">{udise.map((u,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto_auto] gap-2"><input className="input" value={u.udise_code} onChange={e=>updateUdise(i,{udise_code:e.target.value})}/><input className="input" value={u.label||""} placeholder="Label" onChange={e=>updateUdise(i,{label:e.target.value})}/><label className="text-xs flex items-center gap-1"><input type="radio" name="primary" checked={u.is_primary} onChange={()=>updateUdise(i,{is_primary:true})}/>Primary</label><button type="button" className="text-red-600" onClick={()=>setUdise(udise.filter((_,j)=>j!==i))}>Remove</button></div>)}</div></div>
    <div className="md:col-span-2 flex gap-2"><button className="btn-primary" disabled={saving} onClick={()=>void save()}>{saving?"Saving…":"Save Confirmed Correction"}</button><button className="btn-secondary" onClick={()=>{setForm(c||{});setUdise(school.udise_codes||[]);setEditing(false)}}>Cancel</button></div>
   </div>:<div className="grid grid-cols-1 md:grid-cols-3 gap-x-8 gap-y-4 text-sm"><Info label="ERP Code" value={school.code}/><Info label="School Name" value={c?.name}/><Info label="Area / Village" value={c?.area}/><Info label="Area Code" value={c?.area_code}/><Info label="UDISE" value={school.udise_codes?.filter(x=>x.is_active!==false).map(x=>x.udise_code).join(", ")||"Not provided"}/><Info label="Principal / Head" value={c?.principal_head_name}/><Info label="Address" value={[c?.address_line1,c?.address_line2,c?.city,c?.state,c?.pincode].filter(Boolean).join(", ")}/><Info label="Phone" value={c?.phone}/><Info label="Email" value={c?.email}/></div>}
  </section>
  {license&&<section className="card"><h2 className="text-lg font-semibold mb-3">License</h2><div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm"><Info label="Status" value={license.is_valid?"Valid":"Expired / inactive"}/><Info label="Expires" value={new Date(license.expires_at).toLocaleDateString()}/><Info label="Max users" value={String(license.max_users)}/></div></section>}
 </div>;
}
function Info({label,value}:{label:string;value?:string|null}){return <div><div className="text-gray-400 text-xs uppercase tracking-wide">{label}</div><div className="text-gray-800 mt-1">{value||"—"}</div></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="label">{label}</span><input className="input" value={value} onChange={e=>onChange(e.target.value)}/></label>}
