import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { schoolApi, dashboardApi, userAdminApi, rbacApi } from "../services/api";
import { useAuthStore } from "../store/authStore";
import { hasPermission } from "../utils/permissions";
import type { AccountType, RbacRole, School, User } from "../types";
import { apiErrorMessage } from "../utils/apiError";

const LABELS:Record<string,string>={SCHOOL_ADMIN:"School Admin",ACCOUNTS:"Accounts",TEACHER:"Teacher",RECEPTIONIST:"Receptionist"};
const SCHOOL_ADMIN_DESIGNATIONS=["Principal","Headmaster","School Administrator"] as const;

export default function UsersPage(){
 const {schoolId=""}=useParams(); const currentUser=useAuthStore(s=>s.user);
 const [school,setSchool]=useState<School|null>(null); const [organizationName,setOrganizationName]=useState(""); const [users,setUsers]=useState<User[]>([]); const [customRoles,setCustomRoles]=useState<RbacRole[]>([]);
 const [show,setShow]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [saving,setSaving]=useState(false);
 const [form,setForm]=useState({username:"",full_name:"",designation:"",email:"",phone:"",account_type:"TEACHER" as AccountType,custom_role:""});
 const [credential,setCredential]=useState<{username:string;temporary_password:string}|null>(null);
 const [editTarget,setEditTarget]=useState<User|null>(null); const [editForm,setEditForm]=useState({full_name:"",designation:"",email:"",phone:""}); const [editSaving,setEditSaving]=useState(false);
 const [resetTarget,setResetTarget]=useState<User|null>(null); const [resetSaving,setResetSaving]=useState(false);
 const canEdit=hasPermission(currentUser,"user.edit");
 const canResetPassword=!!currentUser&&(currentUser.is_superuser||currentUser.account_type==="ORGANIZATION_ADMIN"||currentUser.account_type==="SCHOOL_ADMIN");
 const allowedTypes=useMemo<AccountType[]>(()=>{
   if(currentUser?.is_superuser||currentUser?.account_type==="ORGANIZATION_ADMIN")return ["SCHOOL_ADMIN","ACCOUNTS","TEACHER","RECEPTIONIST"];
   if(currentUser?.account_type==="SCHOOL_ADMIN")return ["ACCOUNTS","TEACHER","RECEPTIONIST"];
   return [];
 },[currentUser]);

 const load=async()=>{if(!schoolId)return;setError("");try{const [s,us,roles,orgSummary]=await Promise.all([schoolApi.get(schoolId),userAdminApi.list({school_id:schoolId,include_organization_admins:!!currentUser?.is_superuser}),currentUser?.is_superuser?rbacApi.roles(schoolId):Promise.resolve([]),dashboardApi.schoolSummary(schoolId)]);setSchool(s);setOrganizationName(orgSummary.organization_name||"");setUsers(us);setCustomRoles(roles.filter(r=>!r.is_system));setForm(f=>({...f,account_type:allowedTypes.includes(f.account_type)?f.account_type:(allowedTypes[0]||"TEACHER")}));}catch(e){setError(apiErrorMessage(e,"Failed to load users"));}};
 useEffect(()=>{void load();},[schoolId,currentUser?.is_superuser,allowedTypes.join('|')]);

 const submit=async(e:FormEvent)=>{e.preventDefault();if(!school?.organization_id)return;setSaving(true);setError("");setNotice("");try{const created=await userAdminApi.create({username:form.username.trim(),full_name:form.full_name.trim(),designation:form.account_type==="SCHOOL_ADMIN"?(form.designation||"Principal"):null,account_type:form.account_type,email:form.email.trim(),phone:form.phone.trim(),organization_id:school.organization_id,school_id:schoolId,role_codes:form.custom_role?[form.account_type,form.custom_role]:[form.account_type]});if(!created.temporary_password)throw new Error("Temporary password was not returned by the server.");setCredential({username:created.username,temporary_password:created.temporary_password});setShow(false);setForm(f=>({...f,username:"",full_name:"",designation:"",email:"",phone:"",custom_role:""}));setNotice("User created successfully. Copy the one-time temporary password now.");await load();}catch(e){setError(apiErrorMessage(e,"Failed to create user"));}finally{setSaving(false);}};
 const toggle=async(u:User)=>{try{await userAdminApi.update(u.id,{is_active:!u.is_active});setNotice(u.is_active?"User disabled. Existing sessions are revoked.":"User enabled.");await load();}catch(e){setError(apiErrorMessage(e,"Failed to update user"));}};
 const reset=async()=>{if(!resetTarget)return;setResetSaving(true);setError("");try{const result=await userAdminApi.resetPassword(resetTarget.id);setCredential(result);setNotice(`Temporary password reset for ${resetTarget.full_name}. Copy it now.`);setResetTarget(null);}catch(e){setError(apiErrorMessage(e,"Failed to reset password"));}finally{setResetSaving(false);}};
 const canEditTarget=(u:User)=>!!currentUser&&u.id!==currentUser.id&&(currentUser.is_superuser||(currentUser.account_type==="ORGANIZATION_ADMIN"&&!u.is_superuser&&u.account_type!=="ORGANIZATION_ADMIN")||(currentUser.account_type==="SCHOOL_ADMIN"&&["ACCOUNTS","TEACHER","RECEPTIONIST"].includes(u.account_type)));
 const openEdit=(u:User)=>{setEditTarget(u);setEditForm({full_name:u.full_name,designation:u.designation||"",email:u.email||"",phone:u.phone||""});setError("");};
 const saveEdit=async(e:FormEvent)=>{e.preventDefault();if(!editTarget)return;setEditSaving(true);setError("");try{await userAdminApi.update(editTarget.id,{full_name:editForm.full_name.trim(),designation:editTarget.account_type==="SCHOOL_ADMIN"?editForm.designation:null,email:editForm.email.trim()||null,phone:editForm.phone.trim()||null});setNotice(`Profile updated for ${editForm.full_name.trim()}.`);setEditTarget(null);await load();}catch(e){setError(apiErrorMessage(e,"Failed to update user profile"));}finally{setEditSaving(false);}};

 return <div className="space-y-6">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Users</h1><p className="text-gray-500 mt-1">{school?.configuration?.name||school?.code||"School"} · predefined account types and optional Super Admin custom permission profiles.</p></div><div className="flex gap-2">{currentUser?.is_superuser&&<Link className="btn-secondary" to={`/schools/${schoolId}/roles`}>Roles & Permissions</Link>}{hasPermission(currentUser,"user.create")&&<button className="btn-primary" onClick={()=>setShow(!show)}>New User</button>}</div></div>
  {error&&<div className="rounded-lg bg-red-50 border border-red-200 text-red-700 px-4 py-3 text-sm flex flex-wrap items-center justify-between gap-3"><span>{error}</span><button type="button" className="btn-secondary text-xs" onClick={()=>void load()}>Retry</button></div>}{notice&&<div className="rounded-lg bg-green-50 border border-green-200 text-green-800 px-4 py-3 text-sm">{notice}</div>}
  {show&&<form className="card grid grid-cols-1 md:grid-cols-2 gap-4" onSubmit={submit}>
    <ReadOnlyField label="Society/Trust" value={organizationName||"—"}/><ReadOnlyField label="School" value={school?.configuration?.name||school?.code||"—"}/><Field label="Full Name" value={form.full_name} onChange={v=>setForm({...form,full_name:v})}/>{form.account_type==="SCHOOL_ADMIN"&&<label><span className="label">Designation</span><select className="input" value={form.designation||"Principal"} onChange={e=>setForm({...form,designation:e.target.value})}>{SCHOOL_ADMIN_DESIGNATIONS.map(d=><option key={d}>{d}</option>)}</select></label>}<Field label="Username" value={form.username} onChange={v=>setForm({...form,username:v})}/>
    <Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="Phone" value={form.phone} onChange={v=>setForm({...form,phone:v})}/>
    <label><span className="label">Account Type <span className="text-red-600">*</span></span><select className="input" value={form.account_type} onChange={e=>setForm({...form,account_type:e.target.value as AccountType,designation:e.target.value==="SCHOOL_ADMIN"?(form.designation||"Principal"):""})}>{allowedTypes.map(t=><option key={t} value={t}>{LABELS[t]||t}</option>)}</select></label>
    {currentUser?.is_superuser&&<label><span className="label">Custom Permission Profile (Optional)</span><select className="input" value={form.custom_role} onChange={e=>setForm({...form,custom_role:e.target.value})}><option value="">Use predefined permissions only</option>{customRoles.map(r=><option key={r.id} value={r.code}>{r.name} ({r.code})</option>)}</select></label>}
    <div className="md:col-span-2 rounded-lg bg-gray-50 px-4 py-3 text-xs text-gray-600">Parent / Student access is not created here. It is activated from the Student ERP Access workflow using the School-selected mobile number.</div>
    <div className="md:col-span-2"><button className="btn-primary" disabled={saving}>{saving?"Creating…":"Create User"}</button></div>
  </form>}
  {editTarget&&<form className="card border-blue-200" onSubmit={saveEdit}><div className="flex justify-between"><div><h2 className="font-semibold">Edit User Profile</h2><p className="text-sm text-gray-500">{editTarget.username} · {LABELS[editTarget.account_type]||editTarget.account_type}</p></div><button type="button" className="btn-secondary" onClick={()=>setEditTarget(null)}>Cancel</button></div><div className="grid md:grid-cols-2 gap-4 mt-4"><Field label="Full Name" value={editForm.full_name} onChange={v=>setEditForm({...editForm,full_name:v})}/>{editTarget.account_type==="SCHOOL_ADMIN"&&<label><span className="label">Designation</span><select className="input" required value={editForm.designation||"Principal"} onChange={e=>setEditForm({...editForm,designation:e.target.value})}>{SCHOOL_ADMIN_DESIGNATIONS.map(d=><option key={d}>{d}</option>)}</select></label>}<Field label="Email" required={false} type="email" value={editForm.email} onChange={v=>setEditForm({...editForm,email:v})}/><Field label="Phone" value={editForm.phone} onChange={v=>setEditForm({...editForm,phone:v})}/></div><button className="btn-primary mt-4" disabled={editSaving}>{editSaving?"Saving…":"Save Profile"}</button></form>}
  {resetTarget&&<div className="card border-amber-200"><div className="flex justify-between"><div><h2 className="font-semibold">Reset Temporary Password</h2><p className="text-sm text-gray-500">{resetTarget.full_name} · the current temporary password will be invalidated.</p></div><button type="button" className="btn-secondary" onClick={()=>setResetTarget(null)}>Cancel</button></div><button className="btn-primary mt-4" disabled={resetSaving} onClick={()=>void reset()}>{resetSaving?"Resetting…":"Generate New Temporary Password"}</button></div>}
  {credential&&<div className="card border-amber-300"><h2 className="font-semibold">One-time User Credentials</h2><p className="text-sm mt-2">Username: <b>{credential.username}</b></p><p className="text-sm">Temporary Password: <code className="font-mono font-bold">{credential.temporary_password}</code></p><p className="text-xs text-amber-700 mt-2">Copy this now. The plaintext password is not retrievable after this panel is closed. The user must change it at first login.</p><button className="btn-secondary mt-3" onClick={()=>setCredential(null)}>Close</button></div>}
    <div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-2">User</th><th>Login</th><th>Account Type</th><th>Scope</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b last:border-0"><td className="py-3"><div>{u.full_name}</div>{u.designation&&<div className="text-xs text-gray-500">{u.designation}</div>}</td><td className="font-mono text-xs">{u.username}</td><td>{LABELS[u.account_type]||u.account_type}</td><td>{u.account_type==="ORGANIZATION_ADMIN"?"Society/Trust-wide":school?.configuration?.name||school?.code||"School"}</td><td>{u.is_active?"Active":"Disabled"}</td><td><div className="flex gap-2">{canEdit&&canEditTarget(u)&&<button className="btn-secondary text-xs" onClick={()=>openEdit(u)}>Edit Profile</button>}{canResetPassword&&canEdit&&u.id!==currentUser?.id&&<button className="btn-secondary text-xs" onClick={()=>setResetTarget(u)}>Reset Password</button>}{canEdit&&u.id!==currentUser?.id&&<button className="btn-secondary text-xs" onClick={()=>void toggle(u)}>{u.is_active?"Disable":"Enable"}</button>}</div></td></tr>)}</tbody></table>{!users.length&&<div className="py-8 text-center text-gray-500">No users found.</div>}</div>
 </div>;
}
function Field({label,value,onChange,type="text",required=true}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <label><span className="label">{label}{required&&<span className="text-red-600"> *</span>}</span><input className="input" required={required} type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function ReadOnlyField({label,value}:{label:string;value:string}){return <label><span className="label">{label} <span className="text-red-600">*</span></span><input className="input bg-gray-50" value={value} readOnly/></label>}
